[Theme]

DisplayName=Windows 10 ULUTÜRK



[Control Panel\Desktop]

Wallpaper=%SystemRoot%\Web\Wallpaper\ULUTURK\ULUTURK.jpg

WallpaperStyle=2

TileWallpaper=0



[Control Panel\Cursors]

Arrow=%SystemRoot%\Cursors\ULUTURK\turk.ani

Help=%SystemRoot%\Cursors\aero_helpsel.cur

AppStarting=%SystemRoot%\Cursors\aero_working.ani

Wait=%SystemRoot%\Cursors\aero_busy.ani

Crosshair=

IBeam=

NWPen=%SystemRoot%\Cursors\aero_pen.cur

No=%SystemRoot%\Cursors\aero_unavail.cur

SizeNS=%SystemRoot%\Cursors\aero_ns.cur

SizeWE=%SystemRoot%\Cursors\aero_ew.cur

SizeNWSE=%SystemRoot%\Cursors\aero_nwse.cur

SizeNESW=%SystemRoot%\Cursors\aero_nesw.cur

SizeAll=%SystemRoot%\Cursors\aero_move.cur

UpArrow=%SystemRoot%\Cursors\aero_up.cur

Hand=%SystemRoot%\Cursors\aero_link.cur

DefaultValue=Turk Bayragi



[VisualStyles]

Path=%SystemRoot%\Resources\Themes\Aero\Aero.msstyles

ColorStyle=NormalColor

Size=NormalSize



[MasterThemeSelector]

MTSM=DABJDKT

